baseurl: "/torrado-jekyll-site"
permalink: pretty
title: Torrado Equipment
email: torradoequipment@gmail.com
description: "Tu socio confiable en maquinaria agrícola. Más de 20 años especializados en venta, reparación y financiamiento de equipos para optimizar tu operación agrícola en Puerto Rico."
url: "https://www.torradoequipment.com"

logo:
  mobile: "assets/images/company_logo/logomobile.png"
  mobile_height: "50px"
  mobile_width: "50px"
  desktop: "assets/images/company_logo/torradoequipment.png"
  desktop_height: "60px"
  desktop_width: "200px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md